services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    ports:
      - ${NTFY_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone
      - ${NTFY_DIR}/var/cache/ntfy:/var/cache/ntfy
      - ${NTFY_DIR}/etc/ntfy:/etc/ntfy
    command:
      - serve
