services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:5216
    volumes:
      - /etc/timezone:/etc/timezone
      - ./myspeed-data:/myspeed/data
