services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - ${PAGE_PORT}:3000
    volumes:
      - /etc/timezone:/etc/timezone
      - ${DATA_DIR}:/app/config
      - ${IMAGE_DIR}:/app/public/images
      - ${SECRET_DIR}
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOSTS}
